# settings.py
import os
from dotenv import load_dotenv

# Load Environment
load_dotenv()

# --- API KEYS ---
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
MEMBIT_KEY = os.getenv("MEMBIT_API_KEY")
GEMINI_KEY = os.getenv("GEMINI_API_KEY")

# --- API CONFIG ---
CLUSTER_SEARCH_URL = "https://api.membit.ai/v1/clusters/search"
MEMBIT_HEADERS = {
    "X-Membit-Api-Key": MEMBIT_KEY, 
    "User-Agent": "MembitContextAgent/77-Clean"
}

# --- BOT SETTINGS ---
COOLDOWN_SECONDS = int(os.getenv("COOLDOWN_SECONDS", "12"))
COMMANDS_WITH_COOLDOWN = {
    "!hunt", "!analyze", "!trend", "!whatis", 
    "!context", "!compare", "!risk", "!explain", "!graph"
}
HACKATHON_FOOTER = "Insight generated by Membit Cluster Engine x Gemini AI"

# --- RISK KEYWORDS ---
RISK_KEYWORDS = {
    'scam': 40, 'hack': 40, 'exploit': 40, 'phish': 35, 'warning': 25, 
    'fraud': 35, 'airdrop': -10, 'partnership': -7, 'reward': -8, 'upgrade': -6,
}

